### ISSUE TITLE
RingCentral Client issue

### ISSUE THREAD

**Issue by CMCTest** [ringcentral/ringcentral-csharp-client#1]
I have download the c# Client from the below link 
https://github.com/ringcentral/ringcentral-csharp-client

It was giving the below error.

Private RestClient rc; (Unable to resolve the symbol RestClient)

rc.Restapi().Subscription.New (Unable to resolve the symbol Restapi)

I was checking all references added properly and i downloaded the required packages from Nuget Manager.

**Comment by tylerlong** [comment]
@CMCTest  Currently there are two official libraries which allow you to access RingCentral platform API:

### RingCentral SDK

- GitHub: https://github.com/ringcentral/ringcentral-csharp
- NuGet: https://www.nuget.org/packages/RingCentralSDK/

### RingCentral Client

- GitHub: https://github.com/ringcentral/ringcentral-csharp-client
- NuGet: https://www.nuget.org/packages/RingCentral.Client

We recommend you to install them via [NuGet](https://www.nuget.org/) instead of download them from GitHub.

For your specific issue, did you add `using RingCentral;` to the top of your csharp file?

**Comment by CMCTest** [comment]
Hi,

Thank you for the response.

Yes, i have installed the packages from NuGet package manager.
NuGet: https://www.nuget.org/packages/RingCentralSDK/

Yes, I have added the using RingCentral in my top of the code.

I can see the reference RingCentral binary has the method however it is not updating back in the Test application.

Thanks

**Comment by tylerlong** [comment]
@CMCTest  What you installed is the **SDK** but you are reading the docs of the **Client**. Please see my response above for the urls.

The repository for the SDK is here: https://github.com/ringcentral/ringcentral-csharp

**Comment by CMCTest** [comment]
Thanks for the response,

Can you please let me know which one we need to use?

I wanted to see the notification when a new incoming call is received in the Ringcentral Desktop application.

During the notification, i have to call our aspx page to open the phone session in the CRM product.

I have used the NuGet package SDK installed in my solution, should i need to use the Client URL NuGet package in my solution? I have tried this code but notification is not coming up?

sdk = new SDK(appKey, appSecret, SDK.Server.Sandbox, "CMC CTI Test", "");
var platform = sdk.Platform;
sdk.Platform.Login(phoneNumber, "", password, false);
 sub = sdk.CreateSubscription();

sub.NotificationEvent += (sender, e) =>                 {
                     Console.WriteLine(e.Message);
                 };
                 sub.Register();

Can you please help me the same?

Thanks

**Comment by tylerlong** [comment]
You can use either but not necessarily both, but client is now 1.0.0-rc1, not a final release. 

You code is about SDK, so I will close this issue and create a new one here: https://github.com/ringcentral/ringcentral-csharp/issues/54
