### ISSUE TITLE
can not perform asyn call to authorize

### ISSUE THREAD

**Issue by musam8831** [ringcentral/ringcentral-csharp-client#14]
Task&lt;TokenInfo&gt; x = await rc.Authorize("", "", "");

**Comment by tylerlong** [comment]
What's the error message?

**Comment by musam8831** [comment]
Id = 52, Status = WaitingForActivation {1}, Method = "{null}", Result = "{Not yet computed}"
I am getting this response in calling of this method, "Authorize". i tried all three overloaded method. 
Kindly can you please help? 
i also tried "https://github.com/ringcentral/ringcentral-demos-oauth/tree/master/csharp-nancy/csharp-client-nancy"
My Code is below:
//=============
Dim oauth_callback_url = Request.Url.GetLeftPart(UriPartial.Authority) + Request.ApplicationPath + ConfigurationManager.AppSettings("Ringcentral_oauth_callback_url")
            Dim isProduction As Boolean = CType(ConfigurationManager.AppSettings("Ringcentral_isProduction"), Boolean) 'Web.Config read that is it in production or sandbox.
            Dim Appkey As String = "" 
            Dim appSecret As String = "" 

            Dim rc As RestClient = New RestClient(Appkey, appSecret, "https://platform.devtest.ringcentral.com/")
            Dim authCode As String = rc.access_token_ttl

            'Dim token As Task(Of TokenInfo) = rc.Authorize(authCode, oauth_callback_url)
            'Dim token As Task(Of TokenInfo) = rc.Authorize("Email@email.com", "101", "MyPassword")
            'Dim token As Task(Of TokenInfo) = rc.Authorize("SanboxUserNumber", "101", "MyPassword")

**Comment by tylerlong** [comment]
It is because the RingCentral C# client project uses Async massively.

`rc.Authrozie` is an Async method call. I am not an expert on VB.net, when I am writing C# there are two ways to handle this async code:

```
await rc.Authorize(...)
```

or  

```
rc.Authorize(…).Result
```

For VB.net, I did a quick google search and I found this article:  https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/

I think you should write the code as 

```
Dim token as TokenInfo = Await rc.Authorize(…)
```

The following might work too I think:

```
Dim token as TokenInfo = rc.Authorize(…).Result;
```
