### ISSUE TITLE
Access Token expires

### ISSUE THREAD

**Issue by shridharjjoshi86** [ringcentral/ringcentral-csharp-client#47]
Hi,

I have used the RingCentral Client v. 2.3.4.
I have implemented the oAuth authorization to get the access token which is then stored in the DB . We also have set auto refresh token property to true We handled the refresh token event and updated the access token in the database. We use this token from DB to create detailedtelephony event till here every things works fine but after some time might be after couple of hours token get expired. Is there any way so that we can keep this token valid without user intervation.

**Comment by tylerlong** [comment]
@shridharjjoshi86  token does expire by default.

As the approach you described sounds OK to me: 
> We handled the refresh token event and updated the access token in the database. 

Pay attention to data consistency issue: let's say you have two apps accessing the database, one app updates the token in database, how do you sync the token to the other app? Could it be the root cause of your problem?

Another approach is: don't let any of you apps to refresh token. set `rc.AutoRefreshToken = false;` for them. And you have a dedicated process for token refresh. Every app should poll the database for the latest token.
