### ISSUE TITLE
"Object reference not set to instance of an object"

### ISSUE THREAD

**Issue by jmol123** [ringcentral/ringcentral-csharp-client#7]
Hi there,

It appears that my code caught an exception where an "Object reference not set to instance of an object" and the code broke.  It appears that InnerException is null for this exception.  What could cause this exception, and what is the best way to ensure that the code doesn't break (and it resumes normal activity after resolving the exception) when handling the exception?  I haven't stopped the build so if you need any more information, please feel free to reach out to me.

Thank you very much for all your prompt help on these issues.
![error](https://cloud.githubusercontent.com/assets/24798333/22713423/604d068e-ed56-11e6-9f00-aa22bf5af33d.png)

**Comment by tylerlong** [comment]
Before that line of code which causes this exception, there are 3 lines of code printed to the console. Please paste the log messages here.

**Comment by tylerlong** [comment]
I don't think it has anything to do with this repo, it's just a plain C# issue.

I haven't seen the log and inspect the values of the variables. But I guess `exception` is null while you try to access `exception.Message`. 

And the code is different from what I posted originally: https://github.com/ringcentral/ringcentral-csharp-client/issues/5#issuecomment-277174300

Please compare the code and figure out the reason. In my code, I didn't try to access `exception.Message` after `exception = exception.InnerException` while you did. That's why the do...while.. statement failed to avoid the null reference exception.

**Comment by jmol123** [comment]
Hi Tyler, I figured out what caused the exception.  With a particular fax, the Sender was unknown, so when the code attempted the line
`from = message.from.phoneNumber;`
it failed because this field was null.  To prevent this I included an if statement to check to see if the value is null.  This matter has been resolved.  Thanks!!
`var from = "Unknown";
 if (message.from != null)
                    {
                        from = message.from.phoneNumber;
                    }`
